src/main/java/com/dvp/factwebapp/FactBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dvp.factwebapp;

import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 *
 * @author faye
 */
@ManagedBean(name = "fact")
public class FactBean {

	private static final Integer DEFAULT_RANK = 7;
	private Integer rank;
	private Long value;
	private List<FactResult> valueSet;
	private final FactService factService = FactService.getInstance();

	private FactResult calculateFactorial(int rank) {
		final Long factorial = getExactFactorial(rank);
		final Long approximativeValue = factService.calculateFactOfNumberApproximatively(rank);
		final FactResult result = new FactResult(rank, factorial, approximativeValue);
		return result;
	}

	public void calculer() {
		valueSet = new ArrayList<FactResult>(rank);
		for (int index = 1; index <= rank; index++) {
			valueSet.add(calculateFactorial(index));
		}
		value = getExactFactorial(rank);
	}

	private Long getExactFactorial(int rank) {
		return factService.calculateFactOfNumber(rank);
	}

	public Integer getRank() {
		return rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	public Long getValue() {
		return value;
	}

	public List<FactResult> getValueSet() {
		return valueSet;
	}

	public Integer getDefaultRank() {
		return DEFAULT_RANK;
	}

	public List<FactResult> getReverseValues() {

		final List<FactResult> result = new ArrayList<FactResult>();

		for (int i = valueSet.size() - 1; 0 <= i; i--) {
			result.add(valueSet.get(i));
		}

		return result;
	}

}

src/main/java/com/dvp/fibowebapp/FiboBean.java
package com.dvp.fibowebapp;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;

@ManagedBean(name = "fiboBean")
public class FiboBean {

    private static final Integer DEFAULT_RANG = 7;

    private Integer rang;

    private Long valeur;
    private List<FiboResult> valeurs;

    private final FiboService fiboService = FiboService.getInstance();

    public void calculer() {
        System.out.println("Calcul de la suite de Fibonacci pour le rang " + rang);

        // Je calcule d'abord la liste.
        valeurs = new ArrayList<FiboResult>(rang);
        for (int i = 1; i <= rang; i++) {
            final FiboResult fiboResult = calculerFiboResult(i);
            valeurs.add(fiboResult);
        }

        // Puis la valeur pour le rang. Ici j'aurais pu optimiser mais ce n'est
        // pas l'objet de cet article.
        valeur = fiboService.calculerFibonacci(rang);
    }

    private FiboResult calculerFiboResult(Integer rang) {
        final Long valeurExacte = fiboService.calculerFibonacci(rang);
        final Long valeurApproximative = fiboService.calculerApproximationfibonacci(rang);
        final FiboResult fiboResult = new FiboResult(rang, valeurExacte, valeurApproximative);
        return fiboResult;
    }

    /* Getters et setters */
    public Integer getRang() {
        return rang;
    }

    public void setRang(Integer rang) {
        this.rang = rang;
    }

    public Long getValeur() {
        return valeur;
    }

    public List<FiboResult> getValeurs() {
        return valeurs;
    }

    public Integer getDefaultRang() {
        return DEFAULT_RANG;
    }

    public List<FiboResult> getValeursInversees() {

        final List<FiboResult> result = new ArrayList<FiboResult>();

        for (int i = valeurs.size() - 1; 0 <= i; i--) {
            result.add(valeurs.get(i));
        }

        return result;
    }

}

src/main/webapp/home.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    template="/template.xhtml">

    <ui:define name="mainContent">
        <div id="content">Bonjour.</div>
    </ui:define>
</ui:composition>

src/main/webapp/math/factoriel.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
        template="/template.xhtml"
        xmlns:c="http://java.sun.com/jsp/jstl/core">
    
	<ui:define name="mainContent">
        <div id="content">
            <h1>Factorielle</h1>
            <h:form>
                <table>
                    <tr>
                        <td>Rang :</td>
                        <td>
                            <h:selectOneMenu id="factselect" value="#{fact.rank}">
                                <c:forEach var="entry" begin="1" end="100">
                                    <f:selectItem itemLabel="#{entry}" itemValue="#{entry}" />
                                </c:forEach>
                            </h:selectOneMenu>
                        </td>
                        <td>
                            <h:commandButton id="factbutton" value="Calculer" action="#{fact.calculer}"/>
                        </td>
                    </tr>
                </table>
                <c:if test="#{fact.value ne null}">
                    <p>
                        La valeur de la suite de Factorielle pour le rang <b>#{fact.rank}</b>
                        est <b>#{fact.value}</b>.
                    </p>
                </c:if>
                <c:if test="#{fact.valueSet ne null}">
                    <p></p>
                    <table border="1">
                        <thead>
                            <tr>
                                <th>Rang</th>
                                <th>Valeur</th>
                                <th>Valeur approximative</th>
                                <th>Approximation</th>
                            </tr>
                        </thead>
                        <tbody>
                            <c:forEach var="item" items="#{fact.reverseValues}">
                                <tr>
                                    <td>#{item.rank}</td>
                                    <td>#{item.factorial}</td>
                                    <td>#{item.approximativeValue}</td>
                                    <td>#{item.approximation}</td>
                                </tr>
                            </c:forEach>
                        </tbody>
                    </table>
                    <p></p>
                </c:if>
            </h:form>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/math/fibonacci.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:c="http://java.sun.com/jsp/jstl/core" template="/template.xhtml">

    <ui:define name="mainContent">
        <div id="content">
            <h1>Fibonacci</h1>
            <h:form>
                <table>
                    <tr>
                        <td>Rang :</td>
                        <td>
                            <h:selectOneMenu id="fiboselect" value="#{fiboBean.rang}">
                                <c:forEach var="entry" begin="1" end="90">
                                    <f:selectItem itemLabel="#{entry}" itemValue="#{entry}" />
                                </c:forEach>
                            </h:selectOneMenu>
                        </td>
                        <td>
                            <h:commandButton id="fibobutton" value="Calculer" action="#{fiboBean.calculer}"/>
                        </td>
                    </tr>
                </table>
                <c:if test="#{fiboBean.valeur ne null}">
                    <p>
                        La valeur de la suite de Fibonacci pour le rang <b>#{fiboBean.rang}</b>
                        est <b>#{fiboBean.valeur}</b>.
                    </p>
                </c:if>
                <c:if test="#{fiboBean.valeurs ne null}">
                    <p></p>
                    <table border="1">
                        <thead>
                            <tr>
                                <th>Rang</th>
                                <th>Valeur</th>
                                <th>Valeur approximative</th>
                                <th>Approximation</th>
                            </tr>
                        </thead>
                        <tbody>
                            <c:forEach var="item" items="#{fiboBean.valeursInversees}">
                                <tr>
                                    <td>#{item.rang}</td>
                                    <td>#{item.valeurExacte}</td>
                                    <td>#{item.valeurApproximative}</td>
                                    <td>#{item.approximation}</td>
                                </tr>
                            </c:forEach>
                        </tbody>
                    </table>
                    <p></p>
                </c:if>
            </h:form>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:pretty="http://ocpsoft.com/prettyfaces">

    <div id="menus">
        <pretty:link mappingId="fibonacci">Fibonacci</pretty:link><br/>
        <pretty:link mappingId="fibonacci2"><f:param value="10"/>Fibonacci de 10</pretty:link><br/>
        <pretty:link mappingId="fibonacci2"><f:param value="#{fiboBean.defaultRang}"/>
            Fibonacci au rang DEFAULT_RANG
        </pretty:link><br/>
        
        <pretty:link mappingId="factoriel">Factorielle</pretty:link><br/>
        <pretty:link mappingId="factorielOfNumber"><f:param value="10"/>Factorielle de 10</pretty:link><br/>
        <pretty:link mappingId="factorielOfNumber"><f:param value="#{fact.defaultRank}"/>
            Factorielle au rang DEFAULT_RANG
        </pretty:link><br/>
    </div>
</ui:composition>

src/main/webapp/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets">
    
    <f:view contentType="text/html">
        <h:head>
            <title>Fibowebapp</title>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
            <style>
                #menus, #content {
                    border: 2px black solid;
                    padding: 5px;
                    font-family: verdana;
                    font-size: 12px;
                }

                #menus {
                    width: 250px;
                }

                #content {
                    width: 550px;
                    min-height: 300px;
                }

            </style>
        </h:head>
        <h:body id="body">
            <table>
                <tr>
                    <td valign="top">
                        <ui:include src="/menu.xhtml"/>
                    </td>
                    <td valign="top">
                        <ui:insert name="mainContent" />
                    </td>
                </tr>
            </table>
        </h:body>
    </f:view>
</html>